FROM node:10.15.3-alpine as client
WORKDIR /client
COPY client/package.json client/package-lock.json ./
RUN npm ci
COPY client .
RUN npm run build

FROM abiosoft/caddy:no-stats
COPY --from=client client/dist /srv
ADD ./Caddyfile /etc/Caddyfile